name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish NuGet to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./src/TestAndCoverageTarget/TestAndCoverageTarget.csproj

    - name: Build the package
      run: dotnet pack ./src/TestAndCoverageTarget/TestAndCoverageTarget.csproj --configuration Release

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./src/TestAndCoverageTarget/nupkg/*.nupkg --api-key ${GITHUB_TOKEN} --source https://nuget.pkg.github.com/DanBlumenfeld/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
